name: qlm_mobile_suite
description: Professional Suite for QLM Legal Systems - Multi-role & Offline Sync.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core Professional Packages
  dio: ^5.4.1                 # Professional Networking
  provider: ^6.1.1            # State Management
  get_it: ^7.6.7              # Dependency Injection
  sqflite: ^2.3.3             # Local Database
  path: ^1.9.0                # Path helper
  path_provider: ^2.1.2       # Directory helper
  flutter_secure_storage: ^9.0.0 # Secure tokens
  
  # UI & UX
  cupertino_icons: ^1.0.6
  intl: ^0.20.2               # Date & Number formatting
  shimmer: ^3.0.0             # Loading states
  
  # Logic & Data
  uuid: ^4.3.3                # Unique IDs for Offline-First
  json_annotation: ^4.8.1     # Data Mapping
  hive: ^2.2.3                # Faster Cache for simple settings
  hive_flutter: ^1.1.0
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation (Crucial for 50+ column tables)
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
